### ISSUE TITLE
Instant hash_server ban if restarting with expired keys

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/aiopogo#4]
As the API now uses multiple keys you get an instant ban if you still have expired keys in the list

**Comment by Noctem** [comment]
The expired keys should be removed as soon as they receive a 400. [The code](https://github.com/Noctem/aiopogo/blob/v1.5.0/aiopogo/hash_server.py#L150-L161) for that looks okay to me, do you see a problem?

**Comment by Noctem** [comment]
Is there still a problem?
