### ISSUE TITLE
expired hash key isn't displayed

### ISSUE THREAD

**Issue by evenly-epic-mule** [Noctem/aiopogo#5]
instead it shows all hash keys which are in the list

**Comment by Noctem** [comment]
Really? It's [logging `self.instance_token`](https://github.com/Noctem/aiopogo/blob/v1.5.0/aiopogo/hash_server.py#L75) which should be [`next(self._tokens)`](https://github.com/Noctem/aiopogo/blob/v1.5.0/aiopogo/hash_server.py#L123). So I don't see how that could happen, do you?

**Comment by Noctem** [comment]
The issue was actually Monocle logging `conf.HASH_TOKEN` when it caught `ExpiredHashKeyException` (after all keys had expired). Now it will just pass along the message from aiopogo.
